name: GCS Demo

on:
  push:
    branches: [main]

jobs:
  run-with-gcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up GCP credentials
        run: |
          echo "${{ secrets.GCS_SERVICE_ACCOUNT_KEY }}" > gcs-service-account.json
          export GOOGLE_APPLICATION_CREDENTIALS=gcs-service-account.json

